dusk-network/merkle

.github/workflows/build.yml, CHANGELOG.md, Cargo.toml, src/aggregate.rs, src/lib.rs
This is behind the `blake3` feature gate, such that the crate is only required when the feature itself is explicitly required.
Resolves #11
=> Add `Aggregate` impl for `blake3::Hash`

CHANGELOG.md, Cargo.toml, src/lib.rs
This is required to be able to validate a `Tree` when archived to disk.
Resolves #15
=> Fix `CheckBytes` derivation in `Node`

CHANGELOG.md, Cargo.toml, README.md, examples/annotation.rs, src/aggregate.rs, src/lib.rs, src/opening.rs
Change the `Aggregate` trait to include an associated constant called `EMPTY_SUBTREES`. It allows the implementer to provide multiple items to be used in place of `None` when a sub-tree is empty. Height is also no longer provided in `Aggregate::aggregate` - since its purpose was mainly to allow the user to use a "null item" anyway.
This change allows us to change the return of `root` as well, since the root item can now always be set to the first empty item.
=> (Re)introduce multiple null items

CHANGELOG.md
- Add `Tree::walk` allowing a user to walk the tree [#21]
- Add example of generating zero hashes for `blake3`
- Add `EMPTY_SUBTREES` to `Aggregate` trait
- Derive `Debug`, `Clone`, `PartialEq`, `Eq`, and `Hash` for `Tree` and `Opening` [#13]
- Change `Aggregate` trait to bind `Self` to be `Copy`
- Change `Tree::root` to return `&T` as opposed to `Option<&T>`
- Change `Tree` structure by removing `len` field
- Fix `CheckBytes` derivation in `Node` [#15]
[0.1.0]: https://github.com/dusk-network/merkle/releases/tag/v0.1.0
=> Release `0.1.0`

CHANGELOG.md, src/opening.rs
This also changes the branch from `Option<T>` to `T`
=> Prepare `Opening` to be used outside the crate

CHANGELOG.md, Cargo.toml
- Add getters for all fields in `Opening` [#25]
- Add merkle tree implementation with poseidon hash and opening gadget [#29]
- Change opening branch to hold `T` instead of `Option<T>` [#25]
[0.2.0]: https://github.com/dusk-network/merkle/compare/v0.1.0...v0.2.0
=> Release `0.2.0`

CHANGELOG.md, README.md, rust-toolchain.toml, src/lib.rs, src/node.rs, src/opening.rs, src/tree.rs, src/walk.rs
- Return `Ref<T>` from `Tree::root` instead of `&T`
- `Walk` now binds `T` to be `Aggregate`
- Remove `Hash` derivation on `Tree`
Resolves: https://github.com/dusk-network/merkle/issues/37
=> Add lazy computation of node items 

CHANGELOG.md, Cargo.toml
- Documented poseidon related types [#31]
- Modify `Aggregate` to include only one `EMPTY_SUBTREE` [#49]
- Relax `Aggregate` bounds to not be `Copy` [#49]
- Change return of `Tree::smallest_subtree` to `Ref<T>` as opposed to `Option<Ref<T>>` [#49]
[0.4.0]: https://github.com/dusk-network/merkle/compare/v0.3.0...v0.4.0
=> Release `0.4.0`

benches/blake3.rs
The `blake3` insertion benchmark is rewritten to allow for measuring the time of multiple variable insertions. A new benchmark is also introduced that does the same as the insertion benchmark, but also computes the root of the tree at the end of the insertions.
Both of these benchmarks allow for accurate estimation of the root calculation from scratch, given a certain number of elements inserted.
These are the results on a `AMD Ryzen 9 5950X` (3.4 GHz base clock):
```text
blake3_insert_n/10      time:   [6.5373 µs 6.5423 µs 6.5481 µs]
blake3_insert_n/100     time:   [73.387 µs 73.877 µs 74.377 µs]
blake3_insert_n/1000    time:   [1.1084 ms 1.1090 ms 1.1095 ms]
blake3_insert_n/10000   time:   [12.633 ms 12.789 ms 12.948 ms]
blake3_root_n/10        time:   [31.108 µs 31.271 µs 31.422 µs] …
```
=> Add more comprehensive benchmarks

Cargo.toml
- Add more comprehensive benchmarks for `blake3` tree [#54]
- Add `to_var_bytes` and `from_slice` to `Opening` [#55]
- Update to poseidon hash optimized for merkle openings [#62]
=> Bump to `0.4.1-rc.0`

dusk-merkle/CHANGELOG.md, dusk-merkle/Cargo.toml
- Remove features `blake3`, `poseidon` and `zk` [#58]
- Remove `Aggregate` implementations for blake3 and poseidon [#58]
- Add more comprehensive benchmarks for `blake3` tree [#54]
- Add `to_var_bytes` and `from_slice` to `Opening` [#55]
- Update to poseidon hash optimized for merkle openings [#62]
[0.5.0]: https://github.com/dusk-network/merkle/compare/v0.4.0...v0.5.0
=> Bump to `0.5.0`

poseidon-merkle/CHANGELOG.md, poseidon-merkle/Cargo.toml
- Update `dusk-merkle` to `v0.5.0`
[0.2.0]: https://github.com/dusk-network/merkle/compare/poseidon-merkle_v0.1.0...poseidon-merkle_v0.2.0
=> [poseidon] Bump to v0.2.0

poseidon-merkle/Cargo.toml
Keyword section in crates.io had one word too many
=> Remove one keyword for crates.io

poseidon-merkle/CHANGELOG.md, poseidon-merkle/Cargo.toml
Fixed the feature `poseidon-merkle/rkyv-impl`, which didn't cause the activation of `dusk-merkle/rkyv-impl`.
Bump version to `0.2.1-rc.0`
=> poseidon: Fix `rkyv-impl` feature, bump to `v0.2.1-rc.0`

poseidon-merkle/CHANGELOG.md, poseidon-merkle/Cargo.toml
- Update `dusk-bls12_381` to 0.12
- Update `dusk-poseidon` to 0.31
- Update `dusk-plonk` to 0.16
[0.3.0]: https://github.com/dusk-network/merkle/compare/poseidon-merkle_v0.2.1...poseidon-merkle_v0.3.0
=> Release poseidon merkle 0.3.0

dusk-merkle/CHANGELOG.md, dusk-merkle/Cargo.toml
- Remove unused `dusk-bls12_381` dependency
[0.5.1]: https://github.com/dusk-network/merkle/compare/v0.5.0...v0.5.1
=> dusk-merkle: Bump to v0.5.1

dusk-merkle/CHANGELOG.md, dusk-merkle/src/node.rs, dusk-merkle/src/tree.rs
This is achieved by custom implementations of `Archive`, `Serialize` and `Deserialize` for the `Node` struct, avoiding the internal `RefCell`.
Resolves #73
=> dusk-merkle: fix `rkyv` serialization for `Tree`

dusk-merkle/CHANGELOG.md, dusk-merkle/Cargo.toml
- Fix `rkyv` serialization for `Tree` [#73]
[dusk-merkle 0.5.2]: https://github.com/dusk-network/merkle/compare/v0.5.1...v0.5.2
=> Release `0.5.2`

poseidon-merkle/CHANGELOG.md, poseidon-merkle/Cargo.toml
- Update `dusk-bls12_381` to 0.13
- Update `dusk-plonk` to 0.18
- Update `dusk-poseidon` to 0.32
[0.4.0]: https://github.com/dusk-network/merkle/compare/poseidon-merkle_v0.3.0...poseidon-merkle_v0.4.0
=> poseidon-merkle: Bump to v0.4.0

poseidon-merkle/CHANGELOG.md, poseidon-merkle/Cargo.toml
- Update `dusk-plonk` to 0.19
- Update `dusk-poseidon` to 0.33
[0.5.0]: https://github.com/dusk-network/merkle/compare/poseidon-merkle_v0.4.0...poseidon-merkle_v0.5.0
=> poseidon-merkle: Bump to v0.5.0

poseidon-merkle/CHANGELOG.md, poseidon-merkle/Cargo.toml
- Implement `dusk_bytes::Serializable` for `Item<()>`
[poseidon-merkle 0.6.1]: https://github.com/dusk-network/merkle/compare/poseidon-merkle_v0.6.0...poseidon-merkle_v0.6.1
=> poseidon-merkle: bump version to `0.6.1`

poseidon-merkle/CHANGELOG.md, poseidon-merkle/Cargo.toml
- Update `dusk-plonk` to v0.20
- Update `dusk-poseidon` to v0.40
[0.7.0]: https://github.com/dusk-network/merkle/compare/poseidon-merkle_v0.6.1...poseidon-merkle_v0.7.0
=> poseidon-merkle: Bump to v0.7.0

dusk-merkle/CHANGELOG.md, dusk-merkle/src/tree.rs
A panic on an out of bounds insertion is expected in the merkle tree, however, the panic message is a bit cryptic. This commit adds a bounds check (`index < capacity`) and improves the error message such that it is clear to whomever calls it.
Resolves: #91
=> dusk-merkle: add bounds check at `Tree::insert`

dusk-merkle/CHANGELOG.md, dusk-merkle/Cargo.toml
- Add `Default` implementation for `Tree`
- Add bounds check on `Tree::insert`, improving panic message [#91]
[0.5.3]: https://github.com/dusk-network/merkle/compare/v0.5.3...v0.5.3
=> Release `dusk-merkle@0.5.3`

rust-toolchain.toml
For https://github.com/dusk-network/merkle/issues/96.
`rust-toolchain.toml` uses the latest nightly version instead of a fixed one. This PR temporarily solves the problem of the failing lint by setting the rust version to one in which the lint is absent instead of modifying the code. It will be better to update all the rust toolchain versions used across dusk crates and resolve the new linting errors as a separate issue.
As mentioned in https://github.com/dusk-network/safe/pull/27, most dusk crates use a rust version nightly-2023-11-10, so that is the version chosen to be used here, too.
=> Set rust toolchain version to nightly 2023-11-10
